
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.concurrent.TimeUnit;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mustafa
 */
public class varsayilanAyarlar extends javax.swing.JFrame {

    static int satirSayisi;
    static int sutunSayisi;
    static int altinYuzdesi;
    static int gizliAltinYuzdesi;
    static int hamleSayisi;
    static int baslangicAltini;
    static int aHedefBelirlemeMaliyeti;
    static int aHamleMaliyeti;
    static int bHedefBelirlemeMaliyeti;
    static int bHamleMaliyeti;
    static int cHedefBelirlemeMaliyeti;
    static int cHamleMaliyeti;
    static int dHedefBelirlemeMaliyeti;
    static int dHamleMaliyeti;
    static boolean kontrol=true;
    
    static int [][] mevcut_konumlar = new int[4][2];
    static int[][] digerHedefler= new int[3][3];
    
    public varsayilanAyarlar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gereksizLabel = new javax.swing.JLabel();
        oyunAyarlariLabel = new javax.swing.JLabel();
        oyuncuAyarlari = new javax.swing.JLabel();
        satirSutunSayisiPanel = new javax.swing.JPanel();
        sutunSayisiText = new javax.swing.JTextField();
        satirSayisiText = new javax.swing.JTextField();
        sutunSayisiLabel = new javax.swing.JLabel();
        satirSayisiLabel1 = new javax.swing.JLabel();
        altinYuzdeleriPanel = new javax.swing.JPanel();
        varsayilanGizliAltinYuzdesiText = new javax.swing.JTextField();
        varsayilanAltinYuzdesiText = new javax.swing.JTextField();
        varsayilanGizliAltinYuzdesiLabel = new javax.swing.JLabel();
        varsayilanAltinYuzdesiLabel = new javax.swing.JLabel();
        baslangicAltinPanel = new javax.swing.JPanel();
        baslangicAltinText = new javax.swing.JTextField();
        baslangicAltinLabel = new javax.swing.JLabel();
        adimSayisiPanel1 = new javax.swing.JPanel();
        adimSayisiText1 = new javax.swing.JTextField();
        adimSayisiLabel1 = new javax.swing.JLabel();
        dPanel = new javax.swing.JPanel();
        dText2 = new javax.swing.JTextField();
        dText1 = new javax.swing.JTextField();
        dLabel2 = new javax.swing.JLabel();
        dLabel1 = new javax.swing.JLabel();
        aPanel = new javax.swing.JPanel();
        aText3 = new javax.swing.JTextField();
        aText4 = new javax.swing.JTextField();
        aLabel3 = new javax.swing.JLabel();
        aLabel4 = new javax.swing.JLabel();
        bPanel = new javax.swing.JPanel();
        bText3 = new javax.swing.JTextField();
        bText4 = new javax.swing.JTextField();
        bLabel3 = new javax.swing.JLabel();
        bLabel4 = new javax.swing.JLabel();
        cPanel = new javax.swing.JPanel();
        cText3 = new javax.swing.JTextField();
        cText4 = new javax.swing.JTextField();
        cLabel3 = new javax.swing.JLabel();
        cLabel4 = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        aa1 = new javax.swing.JLabel();
        bb1 = new javax.swing.JLabel();
        cc1 = new javax.swing.JLabel();
        baslatButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(760, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        gereksizLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gereksizLabel.setForeground(new java.awt.Color(255, 0, 0));
        gereksizLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gereksizLabel.setText("Varsayılan Ayarlarda Değişiklik Yapma");
        getContentPane().add(gereksizLabel);
        gereksizLabel.setBounds(0, 23, 713, 40);

        oyunAyarlariLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oyunAyarlariLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oyunAyarlariLabel.setText("Oyun Ayarları");
        getContentPane().add(oyunAyarlariLabel);
        oyunAyarlariLabel.setBounds(10, 100, 267, 17);

        oyuncuAyarlari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        oyuncuAyarlari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oyuncuAyarlari.setText("Oyuncu Ayarları");
        getContentPane().add(oyuncuAyarlari);
        oyuncuAyarlari.setBounds(380, 100, 319, 17);

        satirSutunSayisiPanel.setBackground(new java.awt.Color(153, 255, 255));

        sutunSayisiText.setText("20");

        satirSayisiText.setText("20");

        sutunSayisiLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sutunSayisiLabel.setText("Sütun Sayısı : ");

        satirSayisiLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        satirSayisiLabel1.setText("Satır Sayısı : ");

        javax.swing.GroupLayout satirSutunSayisiPanelLayout = new javax.swing.GroupLayout(satirSutunSayisiPanel);
        satirSutunSayisiPanel.setLayout(satirSutunSayisiPanelLayout);
        satirSutunSayisiPanelLayout.setHorizontalGroup(
            satirSutunSayisiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(satirSutunSayisiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(satirSutunSayisiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(satirSutunSayisiPanelLayout.createSequentialGroup()
                        .addComponent(satirSayisiLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(satirSayisiText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(satirSutunSayisiPanelLayout.createSequentialGroup()
                        .addComponent(sutunSayisiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sutunSayisiText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        satirSutunSayisiPanelLayout.setVerticalGroup(
            satirSutunSayisiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, satirSutunSayisiPanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(satirSutunSayisiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satirSayisiLabel1)
                    .addComponent(satirSayisiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(satirSutunSayisiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sutunSayisiLabel)
                    .addComponent(sutunSayisiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        getContentPane().add(satirSutunSayisiPanel);
        satirSutunSayisiPanel.setBounds(10, 130, 267, 143);

        altinYuzdeleriPanel.setBackground(new java.awt.Color(51, 255, 0));

        varsayilanGizliAltinYuzdesiText.setText("10");

        varsayilanAltinYuzdesiText.setText("20");

        varsayilanGizliAltinYuzdesiLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        varsayilanGizliAltinYuzdesiLabel.setText("Gizli Altın Yüzdesi :");

        varsayilanAltinYuzdesiLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        varsayilanAltinYuzdesiLabel.setText("Altin Yüzdesi :");

        javax.swing.GroupLayout altinYuzdeleriPanelLayout = new javax.swing.GroupLayout(altinYuzdeleriPanel);
        altinYuzdeleriPanel.setLayout(altinYuzdeleriPanelLayout);
        altinYuzdeleriPanelLayout.setHorizontalGroup(
            altinYuzdeleriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altinYuzdeleriPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(altinYuzdeleriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(altinYuzdeleriPanelLayout.createSequentialGroup()
                        .addComponent(varsayilanAltinYuzdesiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(varsayilanAltinYuzdesiText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(altinYuzdeleriPanelLayout.createSequentialGroup()
                        .addComponent(varsayilanGizliAltinYuzdesiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varsayilanGizliAltinYuzdesiText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        altinYuzdeleriPanelLayout.setVerticalGroup(
            altinYuzdeleriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altinYuzdeleriPanelLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(altinYuzdeleriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varsayilanAltinYuzdesiLabel)
                    .addComponent(varsayilanAltinYuzdesiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(altinYuzdeleriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varsayilanGizliAltinYuzdesiLabel)
                    .addComponent(varsayilanGizliAltinYuzdesiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        getContentPane().add(altinYuzdeleriPanel);
        altinYuzdeleriPanel.setBounds(10, 300, 267, 143);

        baslangicAltinPanel.setBackground(new java.awt.Color(153, 153, 255));

        baslangicAltinText.setText("200");

        baslangicAltinLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        baslangicAltinLabel.setText("Başlangıç Altını :");

        javax.swing.GroupLayout baslangicAltinPanelLayout = new javax.swing.GroupLayout(baslangicAltinPanel);
        baslangicAltinPanel.setLayout(baslangicAltinPanelLayout);
        baslangicAltinPanelLayout.setHorizontalGroup(
            baslangicAltinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baslangicAltinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(baslangicAltinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(baslangicAltinText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        baslangicAltinPanelLayout.setVerticalGroup(
            baslangicAltinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baslangicAltinPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(baslangicAltinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baslangicAltinLabel)
                    .addComponent(baslangicAltinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        getContentPane().add(baslangicAltinPanel);
        baslangicAltinPanel.setBounds(380, 140, 310, 42);

        adimSayisiPanel1.setBackground(new java.awt.Color(255, 153, 153));

        adimSayisiText1.setText("3");

        adimSayisiLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adimSayisiLabel1.setText("Adım Sayısı : ");

        javax.swing.GroupLayout adimSayisiPanel1Layout = new javax.swing.GroupLayout(adimSayisiPanel1);
        adimSayisiPanel1.setLayout(adimSayisiPanel1Layout);
        adimSayisiPanel1Layout.setHorizontalGroup(
            adimSayisiPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adimSayisiPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adimSayisiLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adimSayisiText1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        adimSayisiPanel1Layout.setVerticalGroup(
            adimSayisiPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adimSayisiPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(adimSayisiPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adimSayisiLabel1)
                    .addComponent(adimSayisiText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        getContentPane().add(adimSayisiPanel1);
        adimSayisiPanel1.setBounds(10, 470, 267, 42);

        dPanel.setBackground(new java.awt.Color(153, 255, 255));

        dText2.setText("5");

        dText1.setText("20");

        dLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dLabel2.setText("Hamle Maliyeti :");

        dLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dLabel1.setText("Hedef Belirleme Maliyeti :");

        javax.swing.GroupLayout dPanelLayout = new javax.swing.GroupLayout(dPanel);
        dPanel.setLayout(dPanelLayout);
        dPanelLayout.setHorizontalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dLabel1))
                .addGap(28, 28, 28)
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dText2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dText1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dPanelLayout.setVerticalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLabel1)
                    .addComponent(dText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLabel2)
                    .addComponent(dText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        getContentPane().add(dPanel);
        dPanel.setBounds(380, 460, 310, 80);

        aPanel.setBackground(new java.awt.Color(153, 255, 255));

        aText3.setText("5");

        aText4.setText("5");

        aLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aLabel3.setText("Hamle Maliyeti :");

        aLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aLabel4.setText("Hedef Belirleme Maliyeti :");

        javax.swing.GroupLayout aPanelLayout = new javax.swing.GroupLayout(aPanel);
        aPanel.setLayout(aPanelLayout);
        aPanelLayout.setHorizontalGroup(
            aPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aLabel4))
                .addGap(28, 28, 28)
                .addGroup(aPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aText3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aText4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aPanelLayout.setVerticalGroup(
            aPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(aPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLabel4)
                    .addComponent(aText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLabel3)
                    .addComponent(aText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        getContentPane().add(aPanel);
        aPanel.setBounds(380, 190, 310, 80);

        bPanel.setBackground(new java.awt.Color(153, 255, 255));

        bText3.setText("5");

        bText4.setText("10");

        bLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bLabel3.setText("Hamle Maliyeti :");

        bLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bLabel4.setText("Hedef Belirleme Maliyeti :");

        javax.swing.GroupLayout bPanelLayout = new javax.swing.GroupLayout(bPanel);
        bPanel.setLayout(bPanelLayout);
        bPanelLayout.setHorizontalGroup(
            bPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLabel4))
                .addGap(28, 28, 28)
                .addGroup(bPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bText3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bText4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bPanelLayout.setVerticalGroup(
            bPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLabel4)
                    .addComponent(bText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLabel3)
                    .addComponent(bText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        getContentPane().add(bPanel);
        bPanel.setBounds(380, 280, 310, 80);

        cPanel.setBackground(new java.awt.Color(153, 255, 255));

        cText3.setText("5");

        cText4.setText("15");

        cLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cLabel3.setText("Hamle Maliyeti :");

        cLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cLabel4.setText("Hedef Belirleme Maliyeti :");

        javax.swing.GroupLayout cPanelLayout = new javax.swing.GroupLayout(cPanel);
        cPanel.setLayout(cPanelLayout);
        cPanelLayout.setHorizontalGroup(
            cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cLabel4))
                .addGap(28, 28, 28)
                .addGroup(cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cText3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cText4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cPanelLayout.setVerticalGroup(
            cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cLabel4)
                    .addComponent(cText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cLabel3)
                    .addComponent(cText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        getContentPane().add(cPanel);
        cPanel.setBounds(380, 370, 310, 80);

        dd.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        dd.setText("D");
        getContentPane().add(dd);
        dd.setBounds(330, 470, 40, 60);

        aa1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        aa1.setText("A");
        getContentPane().add(aa1);
        aa1.setBounds(330, 200, 33, 60);

        bb1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        bb1.setText("B");
        getContentPane().add(bb1);
        bb1.setBounds(330, 290, 33, 60);

        cc1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        cc1.setText("C");
        getContentPane().add(cc1);
        cc1.setBounds(330, 380, 32, 60);

        baslatButon.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        baslatButon.setText("OYUNU BAŞLAT");
        baslatButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baslatButonMouseClicked(evt);
            }
        });
        getContentPane().add(baslatButon);
        baslatButon.setBounds(220, 560, 280, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void baslatButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baslatButonMouseClicked
        satirSayisi = Integer.parseInt(satirSayisiText.getText());
        sutunSayisi = Integer.parseInt(sutunSayisiText.getText());
        
        altinYuzdesi = Integer.parseInt(varsayilanAltinYuzdesiText.getText());
        gizliAltinYuzdesi = Integer.parseInt(varsayilanGizliAltinYuzdesiText.getText());
        
        hamleSayisi = Integer.parseInt(adimSayisiText1.getText());
        
        baslangicAltini = Integer.parseInt(baslangicAltinText.getText());
        
        aHedefBelirlemeMaliyeti = Integer.parseInt(aText4.getText());
        aHamleMaliyeti = Integer.parseInt(aText3.getText());

        bHedefBelirlemeMaliyeti = Integer.parseInt(bText4.getText());
        bHamleMaliyeti = Integer.parseInt(bText3.getText());
        
        cHedefBelirlemeMaliyeti = Integer.parseInt(cText4.getText());
        cHamleMaliyeti = Integer.parseInt(cText3.getText());
        
        dHedefBelirlemeMaliyeti = Integer.parseInt(dText1.getText());
        dHamleMaliyeti = Integer.parseInt(dText2.getText());
        
        
        
        
        
        
       /* mevcut_konumlar[0][0]=0;
        mevcut_konumlar[0][1]=0;
                
        mevcut_konumlar[1][0]=0;
        mevcut_konumlar[1][1]=sutunSayisi-1;
                
        mevcut_konumlar[2][0]=satirSayisi-1;
        mevcut_konumlar[2][1]=sutunSayisi-1;
                
        mevcut_konumlar[3][0]=satirSayisi-1;
        mevcut_konumlar[3][1]=0;
        */
        
         
         this.setVisible(false);
         kontrol=false;
         
        
        
        
        
        
        
    }//GEN-LAST:event_baslatButonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(varsayilanAyarlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(varsayilanAyarlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(varsayilanAyarlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(varsayilanAyarlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new varsayilanAyarlar().setVisible(true);
            }
        });
        
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabel3;
    private javax.swing.JLabel aLabel4;
    private javax.swing.JPanel aPanel;
    private javax.swing.JTextField aText3;
    private javax.swing.JTextField aText4;
    private javax.swing.JLabel aa1;
    private javax.swing.JLabel adimSayisiLabel1;
    private javax.swing.JPanel adimSayisiPanel1;
    private javax.swing.JTextField adimSayisiText1;
    private javax.swing.JPanel altinYuzdeleriPanel;
    private javax.swing.JLabel bLabel3;
    private javax.swing.JLabel bLabel4;
    private javax.swing.JPanel bPanel;
    private javax.swing.JTextField bText3;
    private javax.swing.JTextField bText4;
    private javax.swing.JLabel baslangicAltinLabel;
    private javax.swing.JPanel baslangicAltinPanel;
    private javax.swing.JTextField baslangicAltinText;
    private javax.swing.JButton baslatButon;
    private javax.swing.JLabel bb1;
    private javax.swing.JLabel cLabel3;
    private javax.swing.JLabel cLabel4;
    private javax.swing.JPanel cPanel;
    private javax.swing.JTextField cText3;
    private javax.swing.JTextField cText4;
    private javax.swing.JLabel cc1;
    private javax.swing.JLabel dLabel1;
    private javax.swing.JLabel dLabel2;
    private javax.swing.JPanel dPanel;
    private javax.swing.JTextField dText1;
    private javax.swing.JTextField dText2;
    private javax.swing.JLabel dd;
    private javax.swing.JLabel gereksizLabel;
    private javax.swing.JLabel oyunAyarlariLabel;
    private javax.swing.JLabel oyuncuAyarlari;
    private javax.swing.JLabel satirSayisiLabel1;
    private javax.swing.JTextField satirSayisiText;
    private javax.swing.JPanel satirSutunSayisiPanel;
    private javax.swing.JLabel sutunSayisiLabel;
    private javax.swing.JTextField sutunSayisiText;
    private javax.swing.JLabel varsayilanAltinYuzdesiLabel;
    private javax.swing.JTextField varsayilanAltinYuzdesiText;
    private javax.swing.JLabel varsayilanGizliAltinYuzdesiLabel;
    private javax.swing.JTextField varsayilanGizliAltinYuzdesiText;
    // End of variables declaration//GEN-END:variables
}
